version: '3.9'

services:
  api:
    container_name: mks-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app
      - /app/node_modules
    ports:
      - 3000:3000
    command: ['./docker-entrypoint.sh']
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=pandim
      - DB_NAME=test1
      - DB_PASSWORD=12345
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
    links:
      - redis

  db:
    container_name: db
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pandim
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=test1

  # migration:
  #   build:
  #     context: .
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   env_file: ./.env
  #   environment:
  #     - DB_HOST=db

  redis:
    container_name: cache
    image: redis
    ports:
      - 6380:6380
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
